services:
  - type: worker
    name: terabox-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 land.py
    envVars:
      - key: BOT_TOKEN
        sync: false  # Render dashboard पर set करें