services:
  - type: worker
    name: terabox-bot
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python3 land.py
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false